/**
 * Architect: Task planning and decomposition
 */

import { SessionState, VibeConfig, TaskPlanItem } from '../types.js';
import { runClaude } from '../utils/childProcess.js';
import { fileExists, readFile, readJsonFile, writeFile } from '../utils/file.js';
import { log } from '../logger.js';

/**
 * Run Architect to generate task plan
 */
export async function runArchitect(state: SessionState, config: VibeConfig): Promise<TaskPlanItem[]> {
    log.info('🏗️  [Architect] Planning tasks...');

    // Read requirements and index
    const requirements = fileExists('REQUIREMENTS.md')
        ? readFile('REQUIREMENTS.md')
        : 'Optimize existing codebase based on index.';

    const indexData = readJsonFile(config.indexFile);

    // Use SuperClaude workflow command
    const prompt = `/sc:workflow
Domain: ${state.domain}

Project Index:
${JSON.stringify(indexData, null, 2)}

Requirements:
${requirements}

Constraint: Max ${config.maxParallelAgents} parallel agents, ensure tasks modify different files.
`;

    const result = await runClaude(prompt);

    if (result.code !== 0) {
        throw new Error(`Claude failed: ${result.stderr}`);
    }

    // Read the workflow file generated by SuperClaude
    // Assuming /sc:workflow creates a workflow file, adjust path if needed
    const workflowFile = 'vibe_workflow.json'; // Adjust if SuperClaude uses different filename
    let tasks: TaskPlanItem[];

    try {
        const workflowData = readJsonFile(workflowFile);
        // Extract tasks from workflow data, adjust structure as needed
        tasks = workflowData.tasks || workflowData; // depends on SuperClaude output format

        // Ensure tasks have correct format
        tasks = tasks.map((task: any) => ({
            id: task.id || `task_${Math.random().toString(36).substr(2, 9)}`,
            name: task.name || task.title || 'Unknown Task',
            desc: task.desc || task.description || 'No description'
        }));
    } catch (error) {
        // Fallback: try to parse from stdout if file not created
        throw new Error(`Failed to read workflow from ${workflowFile}: ${error instanceof Error ? error.message : String(error)}`);
    }

    // Write plan file
    writeFile(config.planFile, JSON.stringify(tasks, null, 2));
    log.success(`✅ Plan generated: ${tasks.length} tasks.`);

    return tasks;
}
